targets:
  $default:
    builders:
      orchestrator_generator|network_registry:
        enabled: true

builders:
  network_registry:
    target: ":orchestrator_generator"
    import: "package:orchestrator_generator/orchestrator_generator.dart"
    builder_factories: ["networkRegistryBuilder"]
    build_extensions: {".dart": [".network_registry.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]

  network_job:
    target: ":orchestrator_generator"
    import: "package:orchestrator_generator/orchestrator_generator.dart"
    builder_factories: ["networkJobBuilder"]
    build_extensions: {".dart": [".network_job.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]

  executor_registry:
    target: ":orchestrator_generator"
    import: "package:orchestrator_generator/orchestrator_generator.dart"
    builder_factories: ["executorRegistryBuilder"]
    build_extensions: {".dart": [".executor_registry.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]

  orchestrator:
    target: ":orchestrator_generator"
    import: "package:orchestrator_generator/orchestrator_generator.dart"
    builder_factories: ["orchestratorBuilder"]
    build_extensions: {".dart": [".orchestrator.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]

  async_state:
    target: ":orchestrator_generator"
    import: "package:orchestrator_generator/orchestrator_generator.dart"
    builder_factories: ["asyncStateBuilder"]
    build_extensions: {".dart": [".async_state.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]

  job:
    target: ":orchestrator_generator"
    import: "package:orchestrator_generator/orchestrator_generator.dart"
    builder_factories: ["jobBuilder"]
    build_extensions: {".dart": [".job.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]

  event:
    target: ":orchestrator_generator"
    import: "package:orchestrator_generator/orchestrator_generator.dart"
    builder_factories: ["eventBuilder"]
    build_extensions: {".dart": [".event.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]

  typed_job:
    target: ":orchestrator_generator"
    import: "package:orchestrator_generator/orchestrator_generator.dart"
    builder_factories: ["typedJobBuilder"]
    build_extensions: {".dart": [".typed_job.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]

  orchestrator_provider:
    target: ":orchestrator_generator"
    import: "package:orchestrator_generator/orchestrator_generator.dart"
    builder_factories: ["orchestratorProviderBuilder"]
    build_extensions: {".dart": [".orchestrator_provider.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]
